<?php

/**
 * Teknologi & IT services: custom software, SaaS, hosting, hardware/software
 * resale, IT consulting, and managed services.
 *
 * The seventh value is book availability: intern | both | fiskal.
 * Descriptions are appended as the eighth value from the curated catalog.
 */
$rows = [
    ['1000', 'Aset', 'asset', 'debit', null, false, 'both'],
    ['1100', 'Kas dan Setara Kas', 'asset', 'debit', '1000', false, 'both'],
    ['1101', 'Kas', 'asset', 'debit', '1100', true, 'both'],
    ['1102', 'Bank Operasional', 'asset', 'debit', '1100', true, 'both'],
    ['1103', 'Saldo Payment Gateway', 'asset', 'debit', '1100', true, 'both'],
    ['1104', 'Bank Pajak dan Payroll', 'asset', 'debit', '1100', true, 'both'],
    ['1200', 'Piutang dan Tagihan', 'asset', 'debit', '1000', false, 'both'],
    ['1201', 'Piutang Usaha', 'asset', 'debit', '1200', true, 'both'],
    ['1202', 'Pendapatan Proyek Belum Ditagih', 'asset', 'debit', '1200', true, 'intern'],
    ['1203', 'Cadangan Kerugian Piutang Manajemen', 'asset', 'credit', '1200', true, 'intern'],
    ['1204', 'Piutang Karyawan', 'asset', 'debit', '1200', true, 'both'],
    ['1300', 'Persediaan', 'asset', 'debit', '1000', false, 'both'],
    ['1301', 'Persediaan Hardware IT', 'asset', 'debit', '1300', true, 'both'],
    ['1302', 'Persediaan Lisensi Software', 'asset', 'debit', '1300', true, 'both'],
    ['1400', 'Aset Lancar Lainnya', 'asset', 'debit', '1000', false, 'both'],
    ['1401', 'Biaya Cloud dan Software Dibayar di Muka', 'asset', 'debit', '1400', true, 'both'],
    ['1402', 'PPN Masukan', 'asset', 'debit', '1400', true, 'both'],
    ['1403', 'Pajak Dibayar di Muka', 'asset', 'debit', '1400', true, 'both'],
    ['1404', 'Uang Muka Vendor', 'asset', 'debit', '1400', true, 'both'],
    ['1405', 'Jaminan dan Deposit', 'asset', 'debit', '1400', true, 'both'],
    ['1500', 'Aset Tetap', 'asset', 'debit', '1000', false, 'both'],
    ['1501', 'Komputer dan Perangkat Jaringan', 'asset', 'debit', '1500', true, 'both'],
    ['1502', 'Server dan Peralatan Data Center', 'asset', 'debit', '1500', true, 'both'],
    ['1503', 'Peralatan Kantor', 'asset', 'debit', '1500', true, 'both'],
    ['1504', 'Perangkat Demo dan Lab', 'asset', 'debit', '1500', true, 'both'],
    ['1591', 'Akumulasi Penyusutan Komersial', 'asset', 'credit', '1500', true, 'intern'],
    ['1592', 'Akumulasi Penyusutan Fiskal', 'asset', 'credit', '1500', true, 'fiskal'],
    ['1600', 'Aset Takberwujud', 'asset', 'debit', '1000', false, 'intern'],
    ['1601', 'Pengembangan Produk Software Dikapitalisasi', 'asset', 'debit', '1600', true, 'intern'],
    ['1691', 'Akumulasi Amortisasi Produk Software', 'asset', 'credit', '1600', true, 'intern'],

    ['2000', 'Liabilitas', 'liability', 'credit', null, false, 'both'],
    ['2100', 'Liabilitas Jangka Pendek', 'liability', 'credit', '2000', false, 'both'],
    ['2101', 'Utang Usaha', 'liability', 'credit', '2100', true, 'both'],
    ['2102', 'Pendapatan SaaS dan Hosting Diterima di Muka', 'liability', 'credit', '2100', true, 'both'],
    ['2103', 'Biaya Vendor Masih Harus Dibayar', 'liability', 'credit', '2100', true, 'both'],
    ['2104', 'Uang Muka Pelanggan Proyek', 'liability', 'credit', '2100', true, 'both'],
    ['2105', 'Deposit Pelanggan', 'liability', 'credit', '2100', true, 'both'],
    ['2110', 'PPN Keluaran', 'liability', 'credit', '2100', true, 'both'],
    ['2111', 'Utang PPh 21', 'liability', 'credit', '2100', true, 'both'],
    ['2112', 'Utang PPh 23', 'liability', 'credit', '2100', true, 'both'],
    ['2113', 'Utang PPh Badan', 'liability', 'credit', '2100', true, 'fiskal'],
    ['2114', 'Utang Gaji dan Benefit', 'liability', 'credit', '2100', true, 'both'],
    ['2200', 'Liabilitas Jangka Panjang', 'liability', 'credit', '2000', false, 'both'],
    ['2201', 'Pinjaman Bank', 'liability', 'credit', '2200', true, 'both'],
    ['2202', 'Liabilitas Sewa Peralatan', 'liability', 'credit', '2200', true, 'both'],

    ['3000', 'Ekuitas', 'equity', 'credit', null, false, 'both'],
    ['3101', 'Modal Disetor', 'equity', 'credit', '3000', true, 'both'],
    ['3201', 'Laba Ditahan', 'equity', 'credit', '3000', true, 'both'],
    ['3301', 'Prive atau Dividen', 'equity', 'debit', '3000', true, 'both'],

    ['4000', 'Pendapatan', 'revenue', 'credit', null, false, 'both'],
    ['4101', 'Pendapatan Custom Software', 'revenue', 'credit', '4000', true, 'both'],
    ['4102', 'Pendapatan Langganan SaaS', 'revenue', 'credit', '4000', true, 'both'],
    ['4103', 'Pendapatan Hosting dan Domain', 'revenue', 'credit', '4000', true, 'both'],
    ['4104', 'Penjualan Hardware IT', 'revenue', 'credit', '4000', true, 'both'],
    ['4105', 'Penjualan Lisensi Software', 'revenue', 'credit', '4000', true, 'both'],
    ['4106', 'Pendapatan Konsultasi IT', 'revenue', 'credit', '4000', true, 'both'],
    ['4107', 'Pendapatan Managed IT Services', 'revenue', 'credit', '4000', true, 'both'],
    ['4108', 'Pendapatan Implementasi dan Integrasi Sistem', 'revenue', 'credit', '4000', true, 'both'],
    ['4109', 'Pendapatan Support dan Maintenance', 'revenue', 'credit', '4000', true, 'both'],
    ['4110', 'Pendapatan Keamanan Siber dan Audit TI', 'revenue', 'credit', '4000', true, 'both'],
    ['4111', 'Pendapatan Pelatihan TI', 'revenue', 'credit', '4000', true, 'both'],
    ['4191', 'Pendapatan Akrual Manajemen', 'revenue', 'credit', '4000', true, 'intern'],
    ['4901', 'Pendapatan Lainnya', 'revenue', 'credit', '4000', true, 'both'],

    ['5000', 'Beban Pokok Pendapatan', 'cogs', 'debit', null, false, 'both'],
    ['5101', 'Tenaga Developer Langsung Proyek', 'cogs', 'debit', '5000', true, 'both'],
    ['5102', 'Cloud dan Server Langsung Pelanggan', 'cogs', 'debit', '5000', true, 'both'],
    ['5103', 'Domain dan Lisensi untuk Dijual Kembali', 'cogs', 'debit', '5000', true, 'both'],
    ['5104', 'Harga Pokok Hardware IT', 'cogs', 'debit', '5000', true, 'both'],
    ['5105', 'Subkontraktor Proyek IT', 'cogs', 'debit', '5000', true, 'both'],
    ['5106', 'Biaya Payment Gateway', 'cogs', 'debit', '5000', true, 'both'],
    ['5107', 'Lisensi Pihak Ketiga untuk Layanan Pelanggan', 'cogs', 'debit', '5000', true, 'both'],
    ['5108', 'Tenaga Support Langsung Pelanggan', 'cogs', 'debit', '5000', true, 'both'],

    ['6000', 'Beban Operasional', 'expense', 'debit', null, false, 'both'],
    ['6101', 'Beban Gaji', 'expense', 'debit', '6000', true, 'both'],
    ['6102', 'Beban Tunjangan dan BPJS', 'expense', 'debit', '6000', true, 'both'],
    ['6103', 'Honor Tenaga Ahli dan Freelancer', 'expense', 'debit', '6000', true, 'both'],
    ['6201', 'Beban Cloud Internal dan DevOps', 'expense', 'debit', '6000', true, 'both'],
    ['6202', 'Beban Software dan Tools Internal', 'expense', 'debit', '6000', true, 'both'],
    ['6203', 'Beban Internet dan Data Center', 'expense', 'debit', '6000', true, 'both'],
    ['6204', 'Beban Riset dan Eksperimen Produk', 'expense', 'debit', '6000', true, 'both'],
    ['6205', 'Beban Keamanan dan Compliance Internal', 'expense', 'debit', '6000', true, 'both'],
    ['6301', 'Beban Pemasaran Digital', 'expense', 'debit', '6000', true, 'both'],
    ['6302', 'Beban Komisi Penjualan', 'expense', 'debit', '6000', true, 'both'],
    ['6401', 'Beban Sewa dan Utilitas Kantor', 'expense', 'debit', '6000', true, 'both'],
    ['6402', 'Beban Perlengkapan dan Peralatan Kecil', 'expense', 'debit', '6000', true, 'both'],
    ['6403', 'Beban Asuransi', 'expense', 'debit', '6000', true, 'both'],
    ['6501', 'Beban Penyusutan Komersial', 'expense', 'debit', '6000', true, 'intern'],
    ['6502', 'Beban Penyusutan Fiskal', 'expense', 'debit', '6000', true, 'fiskal'],
    ['6601', 'Beban Pelatihan dan Sertifikasi', 'expense', 'debit', '6000', true, 'both'],
    ['6602', 'Beban Perjalanan dan Implementasi', 'expense', 'debit', '6000', true, 'both'],
    ['6603', 'Beban Representasi', 'expense', 'debit', '6000', true, 'both'],
    ['6604', 'Beban Cadangan Kerugian Piutang', 'expense', 'debit', '6000', true, 'intern'],
    ['6605', 'Beban Alokasi Internal Divisi', 'expense', 'debit', '6000', true, 'intern'],
    ['6701', 'Beban Jasa Profesional', 'expense', 'debit', '6000', true, 'both'],
    ['6702', 'Beban Bank dan Administrasi', 'expense', 'debit', '6000', true, 'both'],
    ['6703', 'Beban Legal dan Perizinan', 'expense', 'debit', '6000', true, 'both'],
    ['6704', 'Beban Rekrutmen', 'expense', 'debit', '6000', true, 'both'],
    ['6801', 'Denda dan Sanksi Pajak', 'expense', 'debit', '6000', true, 'intern'],

    ['8000', 'Penyesuaian Fiskal', 'other', 'credit', null, false, 'fiskal'],
    ['8101', 'Koreksi Fiskal Positif', 'revenue', 'credit', '8000', true, 'fiskal'],
    ['8102', 'Koreksi Fiskal Negatif', 'expense', 'debit', '8000', true, 'fiskal'],
    ['8103', 'Beban PPh Badan Fiskal', 'expense', 'debit', '8000', true, 'fiskal'],
];

$descriptions = require dirname(__DIR__).'/coa-descriptions/teknologi.php';

return array_map(
    static fn (array $row): array => [...$row, $descriptions[$row[0]]],
    $rows,
);
