<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { auth } from '$lib/stores/auth.svelte.js';
  import { accountApi, type Account, type AccountInput } from '$lib/api/account.js';
  import { ApiError } from '$lib/api/client.js';
  import CoaTreeNode from '$lib/components/coa/CoaTreeNode.svelte';
  import AccountDescriptionTooltip from '$lib/components/coa/AccountDescriptionTooltip.svelte';
  import Combobox, { type ComboOption } from '$lib/components/ui/Combobox.svelte';

  type ViewMode = 'list' | 'tree' | 'tview';

  interface TreeNode {
    account: Account;
    children: TreeNode[];
  }

  let items = $state<Account[]>([]);
  let viewMode = $state<ViewMode>('list');
  let treeSearch = $state('');
  let listSearch = $state('');
  let filterOpen = $state(false);
  let filterType = $state('');
  let filterNormalBalance = $state('');
  let filterAvailability = $state('');
  let filterStatus = $state('');
  let filterPostable = $state('');
  let filterFake = $state('');
  let loading = $state(true);
  let error = $state<string | null>(null);

  const TYPE_LABEL: Record<string, string> = {
    asset: 'Aktiva',
    liability: 'Kewajiban',
    equity: 'Ekuitas',
    revenue: 'Pendapatan',
    expense: 'Biaya',
    cogs: 'HPP',
    contra_asset: 'Kontra Aktiva',
    contra_liability: 'Kontra Kewajiban',
    contra_equity: 'Kontra Ekuitas',
    contra_revenue: 'Kontra Pendapatan',
  };

  const AVAILABILITY_LABEL: Record<string, string> = {
    intern: 'Intern',
    fiskal: 'Fiskal',
    both: 'Intern & Fiskal',
  };

  const filtered = $derived.by(() => {
    if (!treeSearch.trim()) return items;
    const q = treeSearch.trim().toLowerCase();
    return items.filter(
      (a) =>
        a.code.toLowerCase().includes(q) ||
        a.name.toLowerCase().includes(q) ||
        (a.description?.toLowerCase().includes(q) ?? false),
    );
  });

  const listFiltered = $derived.by(() => {
    const q = listSearch.trim().toLowerCase();

    return items.filter((account) => {
      const matchesSearch =
        !q ||
        account.code.toLowerCase().includes(q) ||
        account.name.toLowerCase().includes(q) ||
        (account.description?.toLowerCase().includes(q) ?? false);

      return (
        matchesSearch &&
        (!filterType || account.type === filterType) &&
        (!filterNormalBalance || account.normal_balance === filterNormalBalance) &&
        (!filterAvailability || account.availability === filterAvailability) &&
        (!filterStatus || (filterStatus === 'active' ? account.is_active : !account.is_active)) &&
        (!filterPostable ||
          (filterPostable === 'postable' ? account.is_postable : !account.is_postable)) &&
        (!filterFake || (filterFake === 'fake' ? account.is_fake : !account.is_fake))
      );
    });
  });

  const activeFilterCount = $derived(
    [
      filterType,
      filterNormalBalance,
      filterAvailability,
      filterStatus,
      filterPostable,
      filterFake,
    ].filter(Boolean).length,
  );

  function buildTree(rows: Account[]): TreeNode[] {
    const byParent = new Map<string, Account[]>();
    for (const a of rows) {
      const k = a.parent_account_id ?? '__root__';
      if (!byParent.has(k)) byParent.set(k, []);
      byParent.get(k)!.push(a);
    }
    const build = (parent: string | null): TreeNode[] =>
      (byParent.get(parent ?? '__root__') ?? [])
        .sort((a, b) => a.code.localeCompare(b.code))
        .map((a) => ({ account: a, children: build(a.id) }));
    return build(null);
  }

  function buildSideTree(rows: Account[], side: 'debit' | 'credit'): TreeNode[] {
    const subset = rows.filter((a) => a.normal_balance === side);
    const ids = new Set(subset.map((a) => a.id));
    const byParent = new Map<string, Account[]>();
    for (const a of subset) {
      const parentKey =
        a.parent_account_id && ids.has(a.parent_account_id) ? a.parent_account_id : '__root__';
      if (!byParent.has(parentKey)) byParent.set(parentKey, []);
      byParent.get(parentKey)!.push(a);
    }
    const build = (parent: string | null): TreeNode[] =>
      (byParent.get(parent ?? '__root__') ?? [])
        .sort((a, b) => a.code.localeCompare(b.code))
        .map((a) => ({ account: a, children: build(a.id) }));
    return build(null);
  }

  const treeData = $derived(buildTree(filtered));
  const debitTree = $derived(buildSideTree(filtered, 'debit'));
  const creditTree = $derived(buildSideTree(filtered, 'credit'));

  let editing = $state<Account | null>(null);
  let creating = $state(false);
  let form = $state<AccountInput>({
    code: '',
    name: '',
    description: '',
    type: 'asset',
    normal_balance: 'debit',
    parent_account_id: null,
    is_postable: true,
    is_active: true,
    availability: 'intern',
    legal_basis: '',
  });
  let formErrors = $state<Record<string, string[]> | null>(null);
  let saving = $state(false);
  let codeAutoGenerated = $state(true);
  const editingId = $derived(editing?.id);
  const editingHasChildren = $derived(
    editingId ? items.some((account) => account.parent_account_id === editingId) : false,
  );

  function isDescendant(accountId: string, ancestorId: string): boolean {
    let current = items.find((account) => account.id === accountId);
    const visited = new Set<string>();
    while (current?.parent_account_id && !visited.has(current.id)) {
      if (current.parent_account_id === ancestorId) return true;
      visited.add(current.id);
      current = items.find((account) => account.id === current!.parent_account_id);
    }
    return false;
  }

  const parentOptions = $derived<ComboOption[]>([
    { id: '', label: 'Akun utama (tanpa parent)' },
    ...items
      .filter(
        (account) =>
          account.id !== editing?.id && (!editing || !isDescendant(account.id, editing.id)),
      )
      .map((account) => ({
        id: account.id,
        label: account.name,
        code: account.code,
        tag: account.is_postable === false ? 'PARENT' : null,
        isFake: account.is_fake,
      })),
  ]);

  function nextAccountCode(parentId: string | null, excludeId?: string): string {
    const siblings = items.filter(
      (account) => (account.parent_account_id ?? null) === parentId && account.id !== excludeId,
    );
    const numericCodes = siblings
      .map((account) => account.code.trim())
      .filter((code) => /^\d+$/.test(code));
    if (numericCodes.length > 0) {
      const lastCode = numericCodes.reduce((max, code) =>
        Number(code) > Number(max) ? code : max,
      );
      return String(Number(lastCode) + 1).padStart(lastCode.length, '0');
    }

    const parent = parentId ? items.find((account) => account.id === parentId) : null;
    if (parent && /^\d+$/.test(parent.code)) return String(Number(parent.code) + 1);

    const rootCodes = items
      .filter((account) => !account.parent_account_id && account.id !== excludeId)
      .map((account) => account.code.trim())
      .filter((code) => /^\d+$/.test(code));
    if (rootCodes.length === 0) return '1000';
    const lastRootCode = rootCodes.reduce((max, code) => (Number(code) > Number(max) ? code : max));
    return String(Number(lastRootCode) + 1).padStart(lastRootCode.length, '0');
  }

  function changeParent(value: string) {
    form.parent_account_id = value || null;
    const parent = value ? items.find((account) => account.id === value) : null;
    if (parent) form.type = parent.type;
    if (creating && codeAutoGenerated) form.code = nextAccountCode(form.parent_account_id);
  }

  async function load() {
    loading = true;
    error = null;
    try {
      items = await accountApi.list('', null, false);
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  }

  onMount(async () => {
    if (!auth.user) {
      const u = await auth.refresh();
      if (!u) {
        goto('/login', { replaceState: true });
        return;
      }
    }
    await load();
  });

  function openCreate() {
    creating = true;
    editing = null;
    codeAutoGenerated = true;
    form = {
      code: nextAccountCode(null),
      name: '',
      description: '',
      type: 'asset',
      normal_balance: 'debit',
      parent_account_id: null,
      is_postable: true,
      is_active: true,
      availability: 'intern',
      legal_basis: '',
    };
    formErrors = null;
  }

  function openEdit(a: Account) {
    creating = false;
    editing = a;
    codeAutoGenerated = false;
    const hasChildren = items.some((account) => account.parent_account_id === a.id);
    form = {
      code: a.code,
      name: a.name,
      description: a.description ?? '',
      type: a.parent_account_id ? (items.find((account) => account.id === a.parent_account_id)?.type ?? a.type) : a.type,
      normal_balance: a.normal_balance,
      parent_account_id: a.parent_account_id,
      is_postable: hasChildren ? false : a.is_postable,
      is_active: a.is_active,
      availability: a.availability,
      legal_basis: a.legal_basis ?? '',
    };
    formErrors = null;
  }

  function closeForm() {
    editing = null;
    creating = false;
    formErrors = null;
    codeAutoGenerated = true;
  }

  async function save() {
    formErrors = null;
    if (form.availability !== 'intern' && !form.legal_basis?.trim()) {
      formErrors = {
        legal_basis: ['Dasar hukum wajib diisi untuk akun Fiskal atau Intern & Fiskal.'],
      };
      return;
    }

    saving = true;
    try {
      if (editing) {
        await accountApi.update(editing.id, form);
      } else {
        await accountApi.create(form);
      }
      closeForm();
      await load();
    } catch (e) {
      if (e instanceof ApiError) {
        const body = e.body as { errors?: Record<string, string[]> } | null;
        formErrors = body?.errors ?? null;
      } else {
        formErrors = { _: [(e as Error).message] };
      }
    } finally {
      saving = false;
    }
  }

  async function destroy(a: Account) {
    if (!confirm(`Hapus akun ${a.code} — ${a.name}?`)) return;
    try {
      await accountApi.destroy(a.id);
      closeForm();
      await load();
    } catch (e) {
      const msg =
        e instanceof ApiError
          ? JSON.stringify((e.body as { errors?: unknown })?.errors ?? e.body)
          : (e as Error).message;
      alert(msg);
    }
  }

  function fieldErr(name: string): string | null {
    return formErrors?.[name]?.[0] ?? null;
  }

  function clearAccountFilters() {
    filterType = '';
    filterNormalBalance = '';
    filterAvailability = '';
    filterStatus = '';
    filterPostable = '';
    filterFake = '';
  }
</script>

<div class="px-6 py-6">
  <header class="mb-5 flex items-center justify-between">
    <div>
      <p class="text-xs font-medium text-text-muted">Master / Akun</p>
      <h1 class="text-2xl font-bold">Bagan Akun</h1>
      <p class="text-sm text-text-muted">{items.length} akun</p>
    </div>
    <button
      type="button"
      class="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white hover:bg-primary-active"
      onclick={openCreate}
      data-testid="account-create"
    >
      + Akun Baru
    </button>
  </header>

  <!-- Tabs + list controls -->
  <div class="mb-3 flex flex-wrap items-center justify-between gap-3">
    <div class="inline-flex rounded-md border border-border-default bg-card-bg p-0.5 text-sm">
      {#each [{ id: 'list', label: 'List' }, { id: 'tree', label: 'Tree' }, { id: 'tview', label: 'T-view' }] as t}
        <button
          type="button"
          class="rounded px-3 py-1.5 font-medium transition-colors {viewMode === t.id
            ? 'bg-primary-light text-primary-active'
            : 'text-text-muted hover:text-text-default'}"
          onclick={() => (viewMode = t.id as ViewMode)}
          data-testid="coa-tab-{t.id}"
        >
          {t.label}
        </button>
      {/each}
    </div>
    {#if viewMode === 'list'}
      <div class="flex min-w-0 flex-1 items-center justify-end gap-2 sm:ml-4">
        <label class="relative min-w-0 flex-1 sm:max-w-md">
          <span class="sr-only">Cari akun</span>
          <svg
            class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-muted"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            aria-hidden="true"
          >
            <circle cx="11" cy="11" r="7"></circle>
            <path d="m20 20-4-4"></path>
          </svg>
          <input
            type="search"
            placeholder="Cari kode, nama, atau deskripsi akun…"
            class="w-full rounded-md border border-border-default bg-card-bg py-1.5 pl-9 pr-3 text-sm focus:border-primary focus:outline-none"
            bind:value={listSearch}
            data-testid="account-list-search"
          />
        </label>
        <button
          type="button"
          class="relative inline-flex shrink-0 items-center gap-2 rounded-md border border-border-default bg-card-bg px-3 py-1.5 text-sm font-medium text-text-default hover:border-primary hover:text-primary"
          onclick={() => (filterOpen = true)}
          aria-label="Buka filter akun"
          data-testid="account-filter-button"
        >
          <svg
            class="h-4 w-4"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            aria-hidden="true"
          >
            <path d="M4 6h16M7 12h10M10 18h4"></path>
          </svg>
          <span class="hidden sm:inline">Filter</span>
          {#if activeFilterCount > 0}
            <span
              class="inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-primary px-1 text-[10px] font-bold text-white"
            >
              {activeFilterCount}
            </span>
          {/if}
        </button>
      </div>
    {:else}
      <input
        type="search"
        placeholder="Cari kode, nama, atau deskripsi akun…"
        class="w-72 rounded-md border border-border-default bg-card-bg px-3 py-1.5 text-sm focus:outline-none focus:border-primary"
        bind:value={treeSearch}
      />
    {/if}
  </div>

  {#if loading}
    <div class="text-text-muted">Memuat…</div>
  {:else if error}
    <div class="rounded-md border border-danger bg-danger-light p-3 text-sm text-danger">
      {error}
    </div>
  {:else if viewMode === 'list'}
    <div
      class="max-h-[calc(100vh-14rem)] overflow-auto overscroll-contain rounded-lg border border-border-default bg-card-bg shadow-xs"
    >
      <table class="ak-table">
        <thead>
          <tr>
            <th>Kode</th>
            <th>Nama</th>
            <th>Tipe</th>
            <th>Normal</th>
            <th class="text-center">Postable</th>
            <th class="text-center">Aktif</th>
            <th class="text-center">Ketersediaan</th>
          </tr>
        </thead>
        <tbody>
          {#each listFiltered as a (a.id)}
            {@const isParent = items.some((child) => child.parent_account_id === a.id)}
            <tr
              class="group/account cursor-pointer"
              onclick={() => openEdit(a)}
              aria-label={`${a.code} ${a.name}. ${a.description ?? 'Deskripsi akun belum diisi.'}`}
              aria-describedby={`account-description-${a.id}`}
            >
              <td class="font-mono">
                <span class="inline-flex items-center gap-2">
                  {#if a.is_fake}
                    <span
                      class="h-1.5 w-1.5 shrink-0 rounded-full bg-text-muted/60"
                      title="Akun hasil import fake data"
                      aria-label="Akun fake"
                    ></span>
                  {:else}
                    <span class="h-1.5 w-1.5 shrink-0" aria-hidden="true"></span>
                  {/if}
                  {a.code}
                </span>
              </td>
              <td>
                <span class="relative inline-block max-w-full align-bottom">
                  <span class="block truncate {isParent ? 'font-semibold text-text-strong' : ''}"
                    >{a.name}</span
                  >
                  <AccountDescriptionTooltip
                    id={`account-description-${a.id}`}
                    description={a.description}
                  />
                </span>
              </td>
              <td class="capitalize">{TYPE_LABEL[a.type] ?? a.type}</td>
              <td>
                <span
                  class="ak-pill {a.normal_balance === 'debit'
                    ? 'bg-info-light text-info'
                    : 'bg-warning-light text-warning'}"
                >
                  {a.normal_balance}
                </span>
              </td>
              <td class="text-center">{a.is_postable ? '✓' : '—'}</td>
              <td class="text-center">{a.is_active ? '✓' : '—'}</td>
              <td class="text-center">
                <span
                  class="inline-flex items-center rounded-full px-1.5 py-0.5 text-[10px] font-semibold {a.availability ===
                  'both'
                    ? 'bg-gradient-to-r from-[#22c55e] to-[#facc15] text-white'
                    : a.availability === 'intern'
                      ? 'bg-paid-light text-paid'
                      : 'bg-[#fff0b8] text-[#8a5a00]'}"
                >
                  {AVAILABILITY_LABEL[a.availability] ?? a.availability}
                </span>
              </td>
            </tr>
          {:else}
            <tr
              ><td colspan="7" class="px-4 py-10 text-center text-text-muted"
                >{listSearch || activeFilterCount > 0
                  ? 'Tidak ada akun yang sesuai dengan filter.'
                  : 'Belum ada akun.'}</td
              ></tr
            >
          {/each}
        </tbody>
      </table>
    </div>
  {:else if viewMode === 'tree'}
    <div class="rounded-lg border border-border-default bg-card-bg shadow-xs">
      <div
        class="grid grid-cols-[1fr_8rem_5rem_3.5rem_3.5rem_6rem] gap-2 border-b border-border-default bg-page-bg px-3 py-2 text-[0.6875rem] font-semibold uppercase tracking-wider text-text-muted"
      >
        <span>Akun</span>
        <span>Tipe</span>
        <span>Normal</span>
        <span class="text-center">Post</span>
        <span class="text-center">Aktif</span>
        <span class="text-center">Mode</span>
      </div>
      {#each treeData as node (node.account.id)}
        <CoaTreeNode {node} onSelect={openEdit} />
      {:else}
        <div class="px-4 py-10 text-center text-sm text-text-muted">Belum ada akun.</div>
      {/each}
    </div>
  {:else if viewMode === 'tview'}
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
      <section class="rounded-lg border border-border-default bg-card-bg shadow-xs">
        <header
          class="flex items-center justify-between border-b border-border-default bg-info-light px-4 py-2"
        >
          <strong class="text-info">Debit-normal</strong>
          <span class="ak-pill bg-card-bg text-info"
            >{filtered.filter((a) => a.normal_balance === 'debit').length}</span
          >
        </header>
        <div
          class="grid grid-cols-[1fr_8rem_5rem_3.5rem_3.5rem_6rem] gap-2 border-b border-border-soft bg-page-bg px-3 py-2 text-[0.625rem] font-semibold uppercase tracking-wider text-text-muted"
        >
          <span>Akun</span>
          <span>Tipe</span>
          <span>Normal</span>
          <span class="text-center">Post</span>
          <span class="text-center">Aktif</span>
          <span class="text-center">Mode</span>
        </div>
        {#each debitTree as node (node.account.id)}
          <CoaTreeNode {node} onSelect={openEdit} />
        {:else}
          <div class="px-4 py-10 text-center text-sm text-text-muted">Tidak ada.</div>
        {/each}
      </section>

      <section class="rounded-lg border border-border-default bg-card-bg shadow-xs">
        <header
          class="flex items-center justify-between border-b border-border-default bg-warning-light px-4 py-2"
        >
          <strong class="text-warning">Credit-normal</strong>
          <span class="ak-pill bg-card-bg text-warning"
            >{filtered.filter((a) => a.normal_balance === 'credit').length}</span
          >
        </header>
        <div
          class="grid grid-cols-[1fr_8rem_5rem_3.5rem_3.5rem_6rem] gap-2 border-b border-border-soft bg-page-bg px-3 py-2 text-[0.625rem] font-semibold uppercase tracking-wider text-text-muted"
        >
          <span>Akun</span>
          <span>Tipe</span>
          <span>Normal</span>
          <span class="text-center">Post</span>
          <span class="text-center">Aktif</span>
          <span class="text-center">Mode</span>
        </div>
        {#each creditTree as node (node.account.id)}
          <CoaTreeNode {node} onSelect={openEdit} />
        {:else}
          <div class="px-4 py-10 text-center text-sm text-text-muted">Tidak ada.</div>
        {/each}
      </section>
    </div>
  {/if}
</div>

{#if filterOpen}
  <div
    class="fixed inset-0 z-40 flex items-center justify-center bg-black/30 p-4"
    onclick={() => (filterOpen = false)}
    onkeydown={(event) => event.key === 'Escape' && (filterOpen = false)}
    role="presentation"
  >
    <div
      class="w-full max-w-lg rounded-lg bg-card-bg p-5 shadow-lg"
      onclick={(event) => event.stopPropagation()}
      onkeydown={(event) => event.stopPropagation()}
      role="dialog"
      aria-modal="true"
      aria-labelledby="account-filter-title"
      tabindex="-1"
    >
      <div class="mb-4 flex items-start justify-between gap-4">
        <div>
          <h2 id="account-filter-title" class="text-lg font-bold">Filter Akun</h2>
          <p class="mt-1 text-xs text-text-muted">Persempit daftar akun berdasarkan atributnya.</p>
        </div>
        <button
          type="button"
          class="rounded-md p-1 text-xl leading-none text-text-muted hover:bg-page-bg hover:text-text-default"
          onclick={() => (filterOpen = false)}
          aria-label="Tutup filter akun"
        >
          ×
        </button>
      </div>

      <div class="grid gap-3 text-sm sm:grid-cols-2">
        <label>
          <span class="mb-1 block font-medium">Tipe akun</span>
          <select
            class="w-full rounded-md border border-border-default bg-card-bg px-2 py-1.5"
            bind:value={filterType}
          >
            <option value="">Semua tipe</option>
            {#each Object.entries(TYPE_LABEL) as [value, label]}
              <option {value}>{label}</option>
            {/each}
          </select>
        </label>
        <label>
          <span class="mb-1 block font-medium">Saldo normal</span>
          <select
            class="w-full rounded-md border border-border-default bg-card-bg px-2 py-1.5"
            bind:value={filterNormalBalance}
          >
            <option value="">Semua saldo</option>
            <option value="debit">Debit</option>
            <option value="credit">Credit</option>
          </select>
        </label>
        <label>
          <span class="mb-1 block font-medium">Ketersediaan</span>
          <select
            class="w-full rounded-md border border-border-default bg-card-bg px-2 py-1.5"
            bind:value={filterAvailability}
          >
            <option value="">Semua ketersediaan</option>
            <option value="intern">Intern</option>
            <option value="fiskal">Fiskal</option>
            <option value="both">Intern &amp; Fiskal</option>
          </select>
        </label>
        <label>
          <span class="mb-1 block font-medium">Status</span>
          <select
            class="w-full rounded-md border border-border-default bg-card-bg px-2 py-1.5"
            bind:value={filterStatus}
          >
            <option value="">Semua status</option>
            <option value="active">Aktif</option>
            <option value="inactive">Tidak aktif</option>
          </select>
        </label>
        <label>
          <span class="mb-1 block font-medium">Penggunaan</span>
          <select
            class="w-full rounded-md border border-border-default bg-card-bg px-2 py-1.5"
            bind:value={filterPostable}
          >
            <option value="">Semua akun</option>
            <option value="postable">Postable</option>
            <option value="non_postable">Parent / non-postable</option>
          </select>
        </label>
        <label>
          <span class="mb-1 block font-medium">Sumber akun</span>
          <select
            class="w-full rounded-md border border-border-default bg-card-bg px-2 py-1.5"
            bind:value={filterFake}
          >
            <option value="">Semua sumber</option>
            <option value="manual">Manual</option>
            <option value="fake">Import fake data</option>
          </select>
        </label>
      </div>

      <div class="mt-5 flex items-center justify-between gap-3 border-t border-border-default pt-4">
        <button
          type="button"
          class="text-sm font-medium text-text-muted hover:text-text-default"
          onclick={clearAccountFilters}
        >
          Reset filter
        </button>
        <button
          type="button"
          class="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white hover:bg-primary-active"
          onclick={() => (filterOpen = false)}
        >
          Terapkan
        </button>
      </div>
    </div>
  </div>
{/if}

{#if creating || editing}
  <div
    class="fixed inset-0 z-30 flex items-center justify-center bg-black/30 p-4"
    onclick={closeForm}
    onkeydown={(event) => event.key === 'Escape' && closeForm()}
    role="presentation"
  >
    <div
      class="w-full max-w-4xl rounded-lg bg-card-bg p-6 shadow-lg"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
      role="dialog"
      aria-modal="true"
      aria-labelledby="account-form-title"
      tabindex="-1"
    >
      <div class="mb-4 flex items-start justify-between gap-4">
        <h2 id="account-form-title" class="text-lg font-bold">
          {editing ? `Edit Akun ${editing.code}` : 'Akun Baru'}
        </h2>
        <button
          type="button"
          class="rounded-md p-1 text-xl leading-none text-text-muted hover:bg-page-bg hover:text-text-default"
          onclick={closeForm}
          aria-label="Tutup editor akun"
          title="Tutup"
        >
          ×
        </button>
      </div>
      <div class="grid grid-cols-2 gap-3 text-sm">
        <label class="col-span-1">
          <span class="block font-medium mb-1">Tipe</span>
          <select
            class="w-full rounded-md border border-border-default px-2 py-1.5 disabled:cursor-not-allowed disabled:bg-page-bg disabled:text-text-muted"
            bind:value={form.type}
            disabled={!!form.parent_account_id}
          >
            <option value="asset">Asset</option>
            <option value="liability">Liability</option>
            <option value="equity">Equity</option>
            <option value="revenue">Revenue</option>
            <option value="cogs">COGS</option>
            <option value="expense">Expense</option>
          </select>
          {#if form.parent_account_id}
            <span class="mt-1 block text-xs text-text-muted">
              Tipe mengikuti akun parent ({TYPE_LABEL[form.type] ?? form.type}).
            </span>
          {:else}
            <span class="mt-1 block text-xs text-text-muted">Pilih tipe untuk akun utama.</span>
          {/if}
        </label>
        <label class="col-span-1">
          <span class="block font-medium mb-1">Akun Parent</span>
          <Combobox
            options={parentOptions}
            value={form.parent_account_id ?? ''}
            placeholder="Cari kode atau nama akun parent…"
            emptyText="Akun parent tidak ditemukan."
            testId="account-parent"
            onSelect={changeParent}
          />
          <span class="mt-1 block text-xs text-text-muted"
            >Menentukan akun ini berada di bawah kelompok mana.</span
          >
        </label>
        <div
          class="col-span-2 grid grid-cols-[92px_minmax(0,1fr)_auto] items-start gap-x-1 gap-y-2"
        >
          <label>
            <span class="block font-medium mb-1">Kode <span class="text-danger">*</span></span>
            <input
              id="account-code-input"
              class="w-[87px] rounded-md border border-border-default py-1.5 text-left font-mono"
              style="padding-left: 8px !important; padding-right: 0 !important; text-indent: 0;"
              bind:value={form.code}
              oninput={() => (codeAutoGenerated = false)}
            />
            <span class="mt-1 block text-xs text-text-muted">Otomatis</span>
            {#if fieldErr('code')}<span class="text-xs text-danger">{fieldErr('code')}</span>{/if}
          </label>
          <label>
            <span class="block font-medium mb-1">Nama <span class="text-danger">*</span></span>
            <input
              class="w-full rounded-md border border-border-default px-2 py-1.5"
              bind:value={form.name}
            />
            {#if fieldErr('name')}<span class="text-xs text-danger">{fieldErr('name')}</span>{/if}
          </label>
          <label class="ml-4">
            <span class="block font-medium mb-1">Normal Balance</span>
            <div
              class="flex min-h-[34px] items-center gap-1"
              role="radiogroup"
              aria-label="Normal Balance"
            >
              <button
                type="button"
                role="radio"
                aria-checked={form.normal_balance === 'debit'}
                class="ak-pill inline-flex items-center justify-center border-0 px-3 py-1.5 font-semibold uppercase transition {form.normal_balance ===
                  'debit'
                  ? 'bg-info-light text-info'
                  : 'bg-page-bg text-text-muted'}"
                onclick={() => (form.normal_balance = 'debit')}
              >
                debit
              </button>
              <button
                type="button"
                role="radio"
                aria-checked={form.normal_balance === 'credit'}
                class="ak-pill inline-flex items-center justify-center border-0 px-3 py-1.5 font-semibold uppercase transition {form.normal_balance ===
                  'credit'
                  ? 'bg-warning-light text-warning'
                  : 'bg-page-bg text-text-muted'}"
                onclick={() => (form.normal_balance = 'credit')}
              >
                credit
              </button>
            </div>
          </label>
        </div>
        <label class="col-span-2">
          <span class="block font-medium mb-1">Deskripsi akun</span>
          <textarea
            class="min-h-40 w-full resize-y rounded-md border border-border-default px-3 py-2 leading-6"
            bind:value={form.description}
            maxlength="2000"
            placeholder="Definisi akun, kapan digunakan, dan contoh peristiwa ekonominya."
          ></textarea>
          <span class="mt-1 block text-xs text-text-muted">
            Gunakan informasi faktual yang membantu operator memilih akun dengan tepat. Deskripsi
            ini tampil sebagai tooltip pada bagan akun.
          </span>
          {#if fieldErr('description')}<span class="text-xs text-danger"
              >{fieldErr('description')}</span
            >{/if}
        </label>
        <div
          class="col-span-2 grid gap-3 rounded-md border border-border-soft bg-page-bg/40 p-3 md:grid-cols-2"
        >
          <div>
            <span class="block font-medium">Ketersediaan akun</span>
            <span class="mt-0.5 block text-xs text-text-muted">
              Tentukan mode jurnal yang boleh memakai akun ini.
            </span>
            <div class="mt-3 flex flex-wrap gap-2" role="radiogroup" aria-label="Ketersediaan akun">
              <button
                type="button"
                role="radio"
                aria-checked={form.availability === 'intern'}
                class="rounded-full border px-3 py-1.5 text-xs font-semibold transition {form.availability ===
                'intern'
                  ? 'border-paid bg-paid-light text-paid ring-2 ring-paid/20'
                  : 'border-border-default bg-page-bg text-text-muted hover:border-text-muted hover:bg-page-bg'}"
                onclick={() => (form.availability = 'intern')}
              >
                Intern
              </button>
              <button
                type="button"
                role="radio"
                aria-checked={form.availability === 'both'}
                class="rounded-full border px-3 py-1.5 text-xs font-semibold transition {form.availability ===
                'both'
                  ? 'border-[#8fbd35] bg-gradient-to-r from-[#22c55e] to-[#facc15] text-white ring-2 ring-[#8fbd35]/25'
                  : 'border-border-default bg-page-bg text-text-muted hover:border-text-muted hover:bg-page-bg'}"
                onclick={() => (form.availability = 'both')}
              >
                Intern &amp; Fiskal
              </button>
              <button
                type="button"
                role="radio"
                aria-checked={form.availability === 'fiskal'}
                class="rounded-full border px-3 py-1.5 text-xs font-semibold transition {form.availability ===
                'fiskal'
                  ? 'border-[#e7b818] bg-[#fff0b8] text-[#8a5a00] ring-2 ring-[#e7b818]/25'
                  : 'border-border-default bg-page-bg text-text-muted hover:border-text-muted hover:bg-page-bg'}"
                onclick={() => (form.availability = 'fiskal')}
              >
                Fiskal
              </button>
            </div>
            {#if form.availability === 'intern'}
              <span class="mt-1 block text-xs text-text-muted"
                >Hanya muncul pada jurnal intern.</span
              >
            {:else if form.availability === 'fiskal'}
              <span class="mt-1 block text-xs text-text-muted"
                >Hanya muncul pada jurnal fiskal.</span
              >
            {:else}
              <span class="mt-1 block text-xs text-text-muted">Muncul pada kedua jenis jurnal.</span
              >
            {/if}
          </div>
          <div class="grid content-start gap-2">
            <div
              class="flex items-center gap-2 rounded-md border border-border-soft bg-page-bg p-3"
            >
              <button
                type="button"
                class="ak-toggle ak-toggle--primary"
                class:ak-toggle--on={form.is_active}
                role="switch"
                aria-checked={form.is_active}
                aria-label="Aktif"
                onclick={() => (form.is_active = !form.is_active)}
              ></button>
              <span>
                <span class="block font-medium">Aktif</span>
                <span class="block text-xs text-text-muted">Tersedia untuk transaksi baru</span>
              </span>
            </div>
            <div
              class="flex items-center gap-2 rounded-md border border-border-soft bg-page-bg p-3 {editingHasChildren
                ? 'cursor-not-allowed opacity-60'
                : ''}"
            >
              <button
                type="button"
                class="ak-toggle ak-toggle--primary"
                class:ak-toggle--on={form.is_postable}
                role="switch"
                aria-checked={form.is_postable}
                aria-label="Postable"
                disabled={editingHasChildren}
                onclick={() => (form.is_postable = !form.is_postable)}
              ></button>
              <span>
                <span class="block font-medium">Postable</span>
                <span class="block text-xs text-text-muted"
                  >{editingHasChildren
                    ? 'Parent tidak dapat dipakai pada baris jurnal'
                    : 'Bisa dipakai pada baris jurnal'}</span
                >
              </span>
            </div>
          </div>
        </div>
      </div>

      {#if form.availability !== 'intern'}
        <label class="mt-3 block text-sm">
          <span class="mb-1 block font-medium">
            Dasar hukum <span class="text-danger">*</span>
          </span>
          <textarea
            class="min-h-24 w-full resize-y rounded-md border border-border-default px-3 py-2 leading-6"
            bind:value={form.legal_basis}
            maxlength="2000"
            required
            aria-invalid={!!fieldErr('legal_basis')}
            placeholder="Contoh: UU PPh Pasal 6 ayat (1)"
          ></textarea>
          <span class="mt-1 block text-xs text-text-muted">
            Cantumkan regulasi atau ketentuan pajak yang menjadi dasar penggunaan akun ini.
          </span>
          {#if fieldErr('legal_basis')}
            <span class="text-xs text-danger">{fieldErr('legal_basis')}</span>
          {/if}
        </label>
      {/if}

      <div class="mt-5 flex items-center justify-between gap-2">
        <div>
          {#if editing}
            <button
              type="button"
              class="rounded-md border border-danger/40 bg-danger-light px-3 py-2 text-sm font-semibold text-danger hover:bg-danger hover:text-white disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:bg-danger-light disabled:hover:text-danger"
              onclick={() => destroy(editing!)}
              disabled={editingHasChildren}
              title={editingHasChildren
                ? 'Parent tidak dapat dihapus selama masih memiliki sub-akun'
                : 'Hapus akun'}
            >
              {editingHasChildren ? 'Parent tidak dapat dihapus' : 'Hapus'}
            </button>
            {#if editingHasChildren}
              <p class="mt-1 max-w-xs text-xs text-text-muted">
                Hapus atau pindahkan semua sub-akun terlebih dahulu.
              </p>
            {/if}
          {/if}
        </div>
        <div class="flex gap-2">
          <button
            type="button"
            class="text-sm text-text-muted hover:text-text-default"
            onclick={closeForm}>Batal</button
          >
          <button
            type="button"
            class="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-white hover:bg-primary-active disabled:opacity-50"
            onclick={save}
            disabled={saving}
          >
            {saving ? 'Menyimpan…' : 'Simpan'}
          </button>
        </div>
      </div>
    </div>
  </div>
{/if}
